version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=&AWS_SECRET_ACCESS_KEY
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dogs_local_proj
    ports:
      - '5454:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data
     
volumes:
  postgres_data: