# Generated by Django 4.1.6 on 2023-10-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
