# Generated by Django 4.1.6 on 2023-10-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trait_app', '0001_initial'),
        ('dog_app', '0002_dog_age_dog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='traits',
            field=models.ManyToManyField(blank=True, to='trait_app.trait'),
        ),
    ]
