# Generated by Django 4.1.6 on 2023-10-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_app', '0002_dog_age_dog_description'),
        ('park_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogpark',
            name='dogs',
            field=models.ManyToManyField(blank=True, to='dog_app.dog'),
        ),
    ]
